FORMAT: 1A

# BootKick 
Kickstarting APIs with Spring Boot.

# Group Notes
Persons related resources of the **BootKick API**

## Persons Collection [/persons/]
### List all Persons [GET]
+ Response 200 (application/json)

        [
            { "id": "123", "name": "Hank Schrader", "phone": "+555687684" },
            { "id": "234", "name": "Jesse Pinkman", "phone": "+555313441" }
        ]

### Create a Person [PUT]
+ Request (application/json)

        { "id": "123", "name": "Hank Schrader", "phone": "+555687684" }

+ Response 204

## Person [/persons/{id}]
A single Person with all its details

+ Parameters
    + id (required, string, `123`) ... `id` of the Person to perform action with. Has example value.

### Retrieve a Person [GET]
+ Response 200 (application/json)

    + Body

            { "id": "123", "name": "Hank Schrader", "phone": "+555687684" }

### Remove a Person [DELETE]
+ Response 204
